# Generated by Django 2.2.9 on 2020-01-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_number',
        ),
    ]
