# Generated by Django 2.2.9 on 2020-01-25 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
